{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crossplane-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-watcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  github_token: {{ .Values.secret.githubToken | required "secret.githubToken is required when existingSecret is empty" | quote }}
{{- end }}
